[workspace]
members = ["lib/sdk", "programs/*"]

resolver = "2"

[workspace.dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"
fixed = { git = "https://github.com/blockworks-foundation/fixed.git", branch = "v1.11.0-borsh0_10-mango" }
pyth-sdk-solana = "0.10"
solana-account-decoder = ">=2.2"
solana-client = ">=2.2"
solana-logger = ">=2.2"
solana-program = ">=2.2"
solana-program-test = ">=2.2"
solana-rpc = ">=2.2"
solana-sdk = ">=2.2"
solana-rpc-client = ">=2.2"
solana-rpc-client-api = ">=2.2"
spl-associated-token-account = "7.0.0"

[profile.release]
codegen-units = 1
lto = "fat"
overflow-checks = true
[profile.release.build-override]
codegen-units = 1
incremental = false
opt-level = 3


[patch.crates-io]
switchboard-solana = { git = "https://github.com/jup-ag/switchboard-solana-sdk.git", rev = "292962367f5320b2b31fce96a39050f6505b2504" }
